beribuku_app/urls.py
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout
from rest_framework import routers
from beribuku_app.views.user.utils import FotoProgramViewSet
from beribuku_app.views.user import index as user_index
from beribuku_app.views.user import program as user_program
from beribuku_app.views.admin import donasi as admin_donasi
from beribuku_app.views.admin import donatur as admin_donatur
from beribuku_app.views.admin import laporan as admin_laporan
from beribuku_app.views.admin import login as admin_login
from beribuku_app.views.admin import main as admin_main
from beribuku_app.views.admin import master as admin_master
from beribuku_app.views.admin import program as admin_program

router = routers.DefaultRouter()
router.register(r'fotos', FotoProgramViewSet)

handler404 = 'beribuku_app.controller.user.index.handler404'

urlpatterns = [
                  url(r'^$', user_index.index, name='user-index'),
                  url(r'^home/', user_index.home, name='user-home'),
                  url(r'^donasi/', user_index.donasi, name='user-donasi'),
                  url(r'^blog/', user_index.blog, name='user-blog'),
                  # url(r'^authenticate/$', beribuku_app.controller.user.index.authenticate, name='authenticate'),
                  # url(r'^proyek/', beribuku_app.controller.user.program.index, name='program'),
                  url(r'^proyek/(?P<id>\d+)/$', user_program.detil, name='program.detil'),
                  url(r'^daftar-proyek/$', user_program.all, name='program-all'),
                  #
                  url(r'^about/', user_index.about, name='user-about'),
                  url(r'^tim/', user_index.tim, name='user-tim'),
                  # url(r'^contact/', beribuku_app.controller.user.index.contact, name='contact'),
                  # url(r'^addDonatur/$', beribuku_app.controller.user.index.addDonatur, name='user.donatur.new'),
                  # url(r'^subscribe/$', beribuku_app.controller.user.index.subscribe, name='user.subscribe'),
                  #
                  url(r'^administration/', include(admin.site.urls)),
                  # url(r'^logout/$', logout, {'next_page': '/admin/login/'}, name='logout'),
                  #
                  # # url admin
                  #
                  url(r'^admin/login/', login, name='admin.login'),
                  #
                  url(r'^admin/logout/', admin_login.logout, name='admin.logout'),

                  url(r'^admin/home/', admin_main.home, name='admin.home'),

                  url(r'^admin/master/', admin_master.index, name='admin.master'),
                  url(r'^admin/newTim/', admin_master.addNewTim, name='admin.master.new'),
                  url(r'^admin/editTim/$', admin_master.editTim, name='admin.master.tim.edit'),
                  url(r'^admin/timDelete/$', admin_master.deleteTim,
                      name='admin.master.deleteTim'),

                  url(r'^admin/newRekening/', admin_master.addNewRekening,
                      name='admin.master.newRekening'),
                  url(r'^admin/editRekening/$', admin_master.editRekening,
                      name='admin.master.rekening.edit'),
                  url(r'^admin/rekDelete/$', admin_master.deleteRekening,
                      name='admin.master.deleteRekening'),

                  url(r'^admin/newAbout/', admin_master.addNewAbout,
                      name='admin.master.newAbout'),
                  url(r'^admin/aboutDelete/$', admin_master.deleteAbout,
                      name='admin.master.deleteAbout'),

                  url(r'^admin/mail/lpj/(?P<programId>\d+)/$', admin_main.mail_lpj,
                      name='admin.mail.lpj'),
                  url(r'^admin/mail/proposal/(?P<programId>\d+)/$', admin_main.mail_proposal,
                      name='admin.mail.proposal'),

                  url(r'^admin/program/$', admin_program.index, name='admin.program'),
                  url(r'^admin/program/(?P<alert>True)/(?P<alert_msg>.*)/$',
                      admin_program.index, name='admin.program.alert'),
                  url(r'^admin/new/', admin_program.addNewProgram, name='admin.program.new'),
                  url(r'^admin/view/$', admin_program.viewProgram, name='admin.program.view'),
                  url(r'^admin/delete/$', admin_program.deleteProgram,
                      name='admin.program.delete'),
                  url(r'^admin/edit/$', admin_program.editProgram, name='admin.program.edit'),
                  url(r'^admin/exceldonatur/(?P<programId>\d+)/$',
                      admin_program.downloadExcelDonatur, name='admin.program.exceldonatur'),
                  url(r'^admin/word/(?P<programId>\d+)/$', admin_program.downloadWord,
                      name='admin.program.word'),

                  url(r'^admin/donatur/$', admin_donatur.index, name='admin.donatur'),
                  url(r'^admin/donatur/(?P<alert>True)/(?P<alert_msg>.*)/$',
                      admin_donatur.index, name='admin.donatur'),
                  url(r'^admin/addDonatur/$', admin_donatur.addDonatur,
                      name='admin.donatur.new'),
                  url(r'^admin/addDonatur/(?P<programId>\d+)/$', admin_donatur.addSpecDonatur,
                      name='admin.donatur.newspec'),
                  url(r'^admin/deleteDonatur/$', admin_donatur.deleteDonatur,
                      name='admin.donatur.delete'),
                  url(r'^admin/editDonatur/$', admin_donatur.editDonatur,
                      name='admin.donatur.edit'),

                  url(r'^admin/donasi/new/(?P<programId>\d+)/$', admin_donasi.addDonasi,
                      name='admin.donasi.new'),

                  url(r'^admin/donasi/uang/view/(?P<programId>\d+)/$',
                      admin_donasi.viewDonasiUang, name='admin.donasi.uang.view'),
                  url(r'^admin/donasi/uang/view/(?P<programId>\d+)/(?P<alert>True)/(?P<alert_msg>.*)/$',
                      admin_donasi.viewDonasiUang, name='admin.donasi.uang.view'),
                  url(r'^admin/donasi/uang/delete/(?P<donasi_id>\d+)/$',
                      admin_donasi.deleteDonasiUang, name='admin.donasi.uang.delete'),
                  url(r'^admin/donasi/uang/edit/(?P<donasi_id>\d+)/$',
                      admin_donasi.editDonasiUang, name='admin.donasi.uang.edit'),

                  url(r'^admin/donasi/buku/view/(?P<programId>\d+)/$',
                      admin_donasi.viewDonasiBuku, name='admin.donasi.buku.view'),
                  url(r'^admin/donasi/buku/view/(?P<programId>\d+)/(?P<alert>True)/(?P<alert_msg>.*)/$',
                      admin_donasi.viewDonasiBuku, name='admin.donasi.buku.view'),
                  url(r'^admin/donasi/buku/delete/(?P<donasi_id>\d+)/$',
                      admin_donasi.deleteDonasiBuku, name='admin.donasi.buku.delete'),
                  url(r'^admin/donasi/buku/edit/(?P<donasi_id>\d+)/$',
                      admin_donasi.editDonasiBuku, name='admin.donasi.buku.edit'),

                  url(r'^admin/donasi/excel/new/(?P<programId>\d+)/$',
                      admin_donasi.addDonasiExcel, name='admin.donasi.new.excel'),

                  url(r'^admin/laporan/$', admin_laporan.index, name='admin.laporan.index'),
                  url(r'^admin/laporan/realisasi/(?P<programId>\d+)/$',
                      admin_laporan.addKeteranganLaporan, name='admin.laporan.add.keterangan'),
                  url(r'^admin/addLaporan/$', admin_laporan.addLaporan,
                      name='admin.laporan.new'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_PATH)

beribuku_com/urls.py
from django.conf import settings
from django.conf.urls import *
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from beribuku_app.views.user.utils import FotoProgramViewSet

router = routers.DefaultRouter()
router.register(r'fotos', FotoProgramViewSet)

handler404  = 'beribuku_app.controller.user.index.handler404'

urlpatterns = [

    url(r'^', include('beribuku_app.urls', namespace='beribuku_app')),
    url(r'^simple-blog/', include('article.urls')),
    url(r'^administration/', include(admin.site.urls)),
        
]

beribuku_app/models.py
from django.db import models
from django.core.validators import RegexValidator
from django import forms
from functools import partial
from django.forms.extras.widgets import SelectDateWidget

from django.utils import timezone

import datetime

# Create your models here.

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class Nama(models.Model):
	alphanumeric = RegexValidator(r'^[a-zA-Z]*$', 'Only alphanumeric characters are allowed.')
	namaDepan = models.CharField(max_length=100, validators=[alphanumeric])
	namaBelakang = models.CharField(max_length=100)

class Akun(models.Model):
	
	username = models.CharField(max_length=100)
	password = models.CharField(max_length=100)

class Program(models.Model):
	nama = models.CharField(max_length=200)
	deskripsi = models.TextField()
	target = models.CharField(max_length=200)
	partner = models.CharField(max_length=200)
	logoPartner = models.FileField(upload_to='static/images/logo')

	def __str__(self):
		return '%s. %s' % (self.id, self.nama)

	@property
	def foto_first(self):
		fotos = self.fotoprogram_set.all()
		if len(fotos) > 0:
			return fotos[0]
		else:
			return None

class FotoProgram(models.Model):
	program = models.ForeignKey('Program')
	gambar = models.FileField(upload_to='static/images/proyek')
	caption = models.CharField(max_length=250, default="")

class Barang(models.Model):
	program = models.ForeignKey('Program')
	nama = models.CharField(max_length=200)
	jumlah = models.CharField(max_length=100, null=True)

class Rekening(models.Model):
	nama = models.CharField(max_length=50)
	noRekening = models.CharField(max_length=50)
	bank = models.CharField(max_length=200)

class Donasi(models.Model):
	program = models.ForeignKey('Program')
	rekening = models.ForeignKey('Rekening')
	deadline = models.DateField()

	def belum_lewat_deadline(self):
		return self.deadline >= datetime.date.today()
 
class Donatur(models.Model):
	program = models.ForeignKey('Program')
	nama = models.CharField(max_length=50)
	email = models.CharField(max_length=50, null=True)
	nohp = models.CharField(max_length=15, null=True)

class Tim(models.Model):
	nama = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	jabatan = models.CharField(max_length=200)
	foto = models.FileField(upload_to='beribuku_app/static/images/tim')

class About(models.Model):
	judul = models.CharField(max_length=100)
	deskripsi = models.CharField(max_length=1200)

class Laporan(models.Model):
	keterangan = models.TextField(null=True)
	program = models.ForeignKey('Program')

class Laporan_temp(models.Model):
	filecontent = models.FileField(upload_to='static/files')

class Laporan_item(models.Model):
	laporan = models.ForeignKey('Laporan')
	keterangan = models.CharField(max_length=1000)
	nominal = models.IntegerField()
	isDebit = models.BooleanField()
	isKredit = models.BooleanField()

class Test(models.Model):
	a = models.IntegerField()

class Donasi_donatur(models.Model):
	donatur = models.ForeignKey('Donatur')
	tanggal = models.DateField()
	konfirmasi = models.BooleanField()
	via = models.CharField(max_length=50, null=True)

class Donasi_uang(models.Model):
	jenis = 'uang'
	donasi_donatur = models.ForeignKey('Donasi_donatur')
	bank = models.CharField(max_length=50, null=True)
	jumlah_uang = models.IntegerField()
	bukti_transfer = models.FileField(upload_to='static/foto/bukti_transfer')

class Donasi_buku(models.Model):
	jenis = 'buku'
	donasi_donatur = models.ForeignKey('Donasi_donatur')
	keterangan = models.CharField(max_length=500, null=True)

class FileMailTemp(models.Model):
	fileUpload = models.FileField(upload_to='static/files')

class Subscriber(models.Model):
	date = models.DateTimeField()
	phone = models.IntegerField()
	email = models.EmailField()

beribuku_app/views/validator.py
import re, html

def escape(s):
	return html.escape(s).strip()

def escape_list(l):
	escaped = []
	print(len(l))
	for i in range(len(l)):
		escaped.append(html.escape(l[i]).strip())

	return escaped

def is_empty(s):
	return s == None or s == ''

def is_number(s):
	try:
		float(s)
		return True
	except ValueError:
		return False

def is_email(s):
	try:
		if re.match(r"[^@]+@[^@]+\.[^@]+", s):
			return True
		else:
			return False
	except:
		return False

def is_image(f):
	try:
		print(f)
		mime =  f.split('/')[0] == 'image'
		print(mime)
		ext = f.split('/')[1] == 'jpg' or f.split('/')[1] == 'png' or f.split('/')[1] == 'gif' or f.split('/')[1] == 'jpeg'
		print(ext)
		return mime and ext
	except Exception as e:
		print(e)
		return False

beribuku_app/templates/2017_design/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    <title>Beri Buku</title>
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static '2017_design/assets/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '2017_design/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static '2017_design/assets/css/font-awesome.min.css' %}">
</head>

<body>
    {% block header %}
    <header>
        <nav class="navbar navbar-default">
                <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'beribuku_app:user-index' %}"><img src="{% static '2017_design/assets/images/beribuku.png' %}"></a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="{{ aktif_proyek }}"><a href="{% url 'beribuku_app:program-all' %}">PROYEK <span class="sr-only">(current)</span></a></li>
                        <li class="{{ aktif_donasi }}"><a href="{% url 'beribuku_app:user-donasi' %}" >DONASI</a></li>
                        <li class="{{ aktif_about }}"><a href="{% url 'beribuku_app:user-about' %}" >TENTANG</a></li>
                        <li class="{{ aktif_blog }}"><a href="{% url 'beribuku_app:user-blog' %}">BLOG</a></li>
                        <li class="{{ aktif_login }}"><a href="{% url 'beribuku_app:admin.login' %}">LOGIN</a></li>
                        <!-- <li><a href="#">FAQ</a></li> -->
                    </ul>
                    <form class="navbar-form navbar-right">
                        <a href="{% url 'beribuku_app:user-donasi' %}" class="btn btn-default btn-red-theme">DONASI SEKARANG</a>
                    </form>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </header>
    {% endblock %}

    {% block content %}
        {#this block is reserved for another content page#}
    {% endblock %}

    {% block carousel %}
        <section id="carousel">
        <div id="carousel-beri-buku" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-beri-buku" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-beri-buku" data-slide-to="1"></li>
                <li data-target="#carousel-beri-buku" data-slide-to="2"></li>
		<li data-target="#carousel-beri-buku" data-slide-to="3"></li>
		<li data-target="#carousel-beri-buku" data-slide-to="4"></li>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="{% static '2017_design/assets/images/children-1.jpg' %}" class="img-responsive">
                    <div class="carousel-caption text-left">
                        <p class="text-left">
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static '2017_design/assets/images/children-2.jpg' %}" class="img-responsive">
                    <div class="carousel-caption text-left">
                        <p class="text-left">
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static '2017_design/assets/images/children-3.jpg' %}" class="img-responsive">
                    <div class="carousel-caption">
                        <p class="text-left">
                        </p>
                    </div>
                </div>
		<div class="item">
                    <img src="{% static '2017_design/assets/images/children-4.jpg' %}" class="img-responsive">
                    <div class="carousel-caption">
                        <p class="text-left">
                        </p>
                    </div>
                </div>
		<div class="item">
                    <img src="{% static '2017_design/assets/images/children-5.jpg' %}" class="img-responsive">
                    <div class="carousel-caption">
                        <p class="text-left">
                        </p>
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-beri-buku" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-beri-buku" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </section>
    {% endblock %}

    {% block project %}
        <section id="project">
        <div class="container">
            <div class="project-description">
                <div class="row grey-text text-center">
                    <h3>APA YANG KAMI LAKUKAN</h3>
                    <div class="col-md-10 col-md-offset-1">
                        <p class="home-text">
                            BeriBuku merupakan sebuah gerakan sosial yang bertujuan menyediakan akses baca bagi setiap anak Indonesia. Kami mengumpulkan dan menyalurkan donasi berupa buku, alat tulis, maupun peralatan untuk perpustakaan dan taman baca yang membutuhkan di seluruh Indonesia. Mari kita buka kunci jendela dunia agar masa depan anak-anak Indonesia lebih cerah nantinya.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    {% endblock %}

    {% block how-to %}
        <section id="how-to">
        <img src="{% static '2017_design/assets/images/children-1.jpg' %}" alt="">
        <div class="container how-to-content">
            <div class="row white-theme-text text-center">
                <div class="col-md-10 col-md-offset-1">
                    <h3>BAGAIMANA CARA BERDONASI DI BERIBUKU</h3>
                    <p class="home-text">Melalui BeriBuku dapat membantu menyediakan buku bagi taman baca atau perpustakaan yang membutuhkan.</p> 
                    <p class="home-text">Caranya sederhana, donasi dapat disalurkan dengan:</p>
                    <br>
                    <p class="home-text">1. Mengirimkan buku anak-anak untuk usia SD dengan menghubungi Ryry (087888614203)</p>
                    <p class="home-text">2. CIMB Niaga Syariah
                        7600-2414-7800
                        a.n. Risma Siti Yusniasari</p>
                    <!-- <button class="btn btn-default btn-red-theme">DONASI SEKARANG</button> -->
                    <h5></h5>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

    {% block project-list %}
        <section id="project-list">
        <div class="container">
            <div class="row">

                {% for program in programs %}
                    <div class="col-md-4">
                        <a href="{% url 'beribuku_app:program.detil' program.id %}" class="thumbnail">
                            <img src="/{{ program.fotoprogram_set.all.0.gambar }}" class="img-responsive">
                            <span class="thumbnail-title white-theme-text uppercase text-center">{{ program.nama }}</span>
                        </a>
                    </div>
                {% endfor %}
            </div><br>
            <div class="row text-right">
                <div class="col-md-12">
                    <a href="{% url 'beribuku_app:program-all' %}" class="grey-text">Lihat semua proyek &gt;</a>
                </div>
            </div>
        </div>

    </section>
    {% endblock %}

    {% block gallery %}
        <section id="gallery">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div id="carousel-gallery" class="carousel slide" data-ride="carousel">
                        <!-- Indicators -->
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-gallery" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-gallery" data-slide-to="1"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            {% for fotos in foto_programs %}
                                <div class="item {% if forloop.counter == 1 %} active {% endif %}">
                                <div class="row">
                                    {% for foto in fotos %}
                                        <div class="col-md-6 gallery-image">
                                            <img src="/{{ foto.gambar }}" class="img-responsive">
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            {% endfor %}
                            <!-- Controls -->
                            <a class="left carousel-control" href="#carousel-gallery" role="button" data-slide="prev">
                                <i class="fa fa-angle-left" aria-hidden="true"></i>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-gallery" role="button" data-slide="next">
                                <i class="fa fa-angle-right" aria-hidden="true"></i>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-info">
                        <div class="panel-heading text-center">
                            <h1 class="panel-title">Twitter</h1>
                        </div>
                        <div class="panel-body">
                            <a class="twitter-timeline"  href="https://twitter.com/_BeriBuku" data-tweet-limit="1" data-widget-id="720810964224880640">Tweet oleh @_BeriBuku</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
    {% block footer %}
        <footer class="blue-theme white-theme-text">
    <div class="container">
        <div class="row">
            <div class="col-md-3 text-right">
                <img src="{% static '2017_design/assets/images/beribuku.png' %}">
            </div>
            <div class="col-md-3">
                <h4>Rekening Donasi</h4>
                <p>
                    CIMB Niaga Syariah <br>
                    76000-2414-7800 <br>
                    a.n Risma Siti Yusniasari
                </p>
            </div>
            <div class="col-md-3">
                <h4>Kontak Kami</h4>
                <p>
                    beribuku@gmail.com <br>
                    Risma 081282365423
                </p>
            </div>
            <div class="col-md-3 social-media">
                <h4>Follow Kami</h4>
                <p>
                    <i class="fa fa-facebook" aria-hidden="true"></i>
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                    <i class="fa fa-instagram" aria-hidden="true"></i>
                </p>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="row text-center">
            <p>
                Copyright &copy; 2018 Beribuku - RSE Fasilkom
            </p>
        </div>
    </div>
    </footer>
    {% endblock %}

<script type="text/javascript" src="{% static '2017_design/assets/js/jquery-2.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static '2017_design/assets/js/bootstrap.min.js' %}"></script>
</body>
</html>

beribuku_app/templates/2017_design/detilProyek.html
{% extends "2017_design/base.html" %}
{% load staticfiles %}

{% block carousel %}
{% endblock %}

{% block project %}
{% endblock %}

{% block how-to %}
{% endblock %}

{% block project-list %}
{% endblock %}

{% block gallery %}
{% endblock %}

{% block content %}
    <section id="simple-act-thumbnail">
        <img style="margin-top:-200px" src="/{{ proyek_selected.foto_first.gambar }}" alt="">
        <div class="container">
            <div class="row white-theme-text text-center">
                <h1>{{ proyek_selected.nama }}</h1>
            </div>
        </div>
    </section>
    <section id="simple-act-content">
        <div class="container">
            <div style="background: white; padding: 50px; margin-left: 200px; margin-right: 200px">
                <p align="justify">{{ proyek_selected.deskripsi }}</p>
            </div>
        </div>
    </section>
{% endblock %}

beribuku_app/templates/2017_design/index.html
{% extends "2017_design/base.html" %}
{% block project-list %}
        <section id="project-list">
        <div class="container">
            
        </div>

    </section>
    {% endblock %}
{% block gallery %}
<section id="gallery">
        <div class="container">

            <div class="row grey-text text-center">
            	<div class="col-md-8">
            		<div class="col-md-12">
		                    <h3 style="padding-top: 0px;">DAFTAR PROYEK YANG TELAH KAMI LAKUKAN</h3>
		                </div>
            		<div class="row">
		                {% for program in programs %}
		                    <div class="col-md-4" style="margin-bottom: 50px;">
		                        <a href="{% url 'beribuku_app:program.detil' program.id %}" class="thumbnail">
		                            <img style="width: 500px; height: 150px;" src="/{{ program.fotoprogram_set.all.0.gambar }}" class="img-responsive">
		                            <span class="thumbnail-title white-theme-text uppercase text-center">{{ program.nama|truncatechars:25 }}</span>
		                        </a>
		                    </div>
		                {% endfor %}
		            </div>
		            <div class="row text-center">
		                <div class="col-md-12">
		                    <a class="btn btn-default btn-red-theme" href="{% url 'beribuku_app:program-all' %}" class="grey-text">Lihat semua proyek</a>
		                </div>
		            </div>
            	</div>
            	<div class="col-md-4">
            		<div class="panel panel-info">
                        <div class="panel-heading text-center">
                            <h1 class="panel-title">Twitter</h1>
                        </div>
                        <div class="panel-body">
                            <a class="twitter-timeline"  href="https://twitter.com/_BeriBuku" data-tweet-limit="1" data-widget-id="720810964224880640">Tweet oleh @_BeriBuku</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                        </div>
                    </div>
            	</div>
            </div>
            </div>
        </div>
    </section>
{% endblock %}